# Generated by Django 5.1.7 on 2025-08-06 23:00

from django.db import migrations, models

import apps.events.validators


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, validators=[apps.events.validators.zero_or_greater_than_1000]
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ManyToManyField(blank=True, related_name="events", to="events.eventcategory"),
        ),
    ]
