# Generated by Django 5.1.7 on 2025-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventcategory_event_image_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
