# Generated by Django 5.1.7 on 2025-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_event_category_alter_tickettype_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="category",
            new_name="categories",
        ),
    ]
