# Generated by Django 5.1.7 on 2025-05-28 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
