# Generated by Django 5.1.7 on 2025-08-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_rename_category_event_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_opening",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
