# Generated by Django 5.1.7 on 2025-08-12 22:29

from django.db import migrations, models

import apps.events.validators


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_registration_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="commission_payer",
            field=models.CharField(choices=[("b", "buyer"), ("s", "seller")], default="s", max_length=3),
        ),
        migrations.AddField(
            model_name="ticket",
            name="commission",
            field=models.DecimalField(decimal_places=0, default=None, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="final_amount",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, validators=[apps.events.validators.zero_or_greater_than_1000]
            ),
        ),
    ]
