# Generated by Django 5.1.7 on 2025-06-03 13:44

import uuid
from django.db import migrations, models


def populate_public_id(apps, schema_editor):
    models = [
        apps.get_model("events", "Event"),
        apps.get_model("events", "EventCategory"),
        apps.get_model("events", "Speaker"),
        apps.get_model("events", "Ticket"),
        apps.get_model("events", "TicketType"),
    ]
    for model in models:
        for object in model.objects.all():
            object.public_id = uuid.uuid4()
            object.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='currency',
            field=models.CharField(choices=[('IRR', 'IRR'), ('IRT', 'IRT')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(populate_public_id, reverse_code=migrations.RunPython.noop),
    ]
