# Generated by Django 5.1.7 on 2025-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'success'), ('c', 'cancelled'), ('e', 'expired')], default='p', max_length=20),
        ),
    ]
