# Generated by Django 5.1.7 on 2025-07-26 14:04

from django.db import migrations, models

import apps.events.validators


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="geo_location",
            field=models.JSONField(blank=True, null=True, validators=[apps.events.validators.geo_location_validator]),
        ),
    ]
