# Generated by Django 5.1.7 on 2025-07-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_payer',
            field=models.CharField(choices=[('b', 'buyer'), ('s', 'seller')], default='s', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
