# Generated by Django 5.1.7 on 2025-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tickettype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
