services:
  backend:
    build:
        context: .
    command: sh -c "make collectstatic && make run address=0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - neshast

  worker:
    build:
      context: .
    command: uv run celery -A config worker -l INFO
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - neshast

  beat:
    build:
      context: .
    command: uv run celery -A config beat -l INFO
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - neshast

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    networks:
      - neshast

  smtp4dev:
    image: rnwood/smtp4dev:3.7.0-ci20250120116
    ports:
      - "5000:80"  # Web UI
      - "2525:25"
    networks:
      - neshast

volumes:
  logs:

networks:
  neshast:

