services:
  backend:
    image: mirsobhan/neshast-backend:latest
    command: sh -c "make collectstatic && make run address=0.0.0.0:8000"
    volumes:
      - logs:/app/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_started
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
      minio:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
    networks:
      - main_net

  postgresql:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  worker:
    image: mirsobhan/neshast-backend:latest
    command: uv run celery -A config worker -l INFO
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - main_net

  beat:
    image: mirsobhan/neshast-backend:latest
    command: uv run celery -A config beat -l INFO
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - main_net

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    networks:
      - main_net

  smtp4dev:
    image: rnwood/smtp4dev:3.7.0-ci20250120116
    ports:
      - "5000:80"  # Web UI
      - "2525:25"
    networks:
      - main_net

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    command: server /data --console-address ":9001"
    networks:
      - main_net

  mc:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minio minio123) do echo 'waiting for minio'; sleep 3; done;
      /usr/bin/mc mb --ignore-existing myminio/static myminio/media;
      "
    networks:
      - main_net

volumes:
  logs:

networks:
  main_net:
    external:
      true
