services:
  backend:
    build:
        context: .
    command: sh -c "make collectstatic && make run address=0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
      minio:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
    networks:
      - neshast

  worker:
    build:
      context: .
    command: uv run celery -A config worker -l INFO
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - neshast

  beat:
    build:
      context: .
    command: uv run celery -A config beat -l INFO
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      smtp4dev:
        condition: service_started
    networks:
      - neshast

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    networks:
      - neshast

  smtp4dev:
    image: rnwood/smtp4dev:3.7.0-ci20250120116
    ports:
      - "5000:80"  # Web UI
      - "2525:25"
    networks:
      - neshast

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_STORAGE_SECRET_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    command: server /data --console-address ":9001"
    networks:
      - neshast

  mc:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 ${MINIO_STORAGE_ACCESS_KEY} ${MINIO_STORAGE_SECRET_KEY}) do echo 'waiting for minio'; sleep 3; done;
      /usr/bin/mc mb --ignore-existing myminio/static myminio/media;
      "
    networks:
      - neshast

volumes:
  logs:

networks:
  neshast:

