services:
  backend:
    build: .
    command: sh -c "make run address=0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started

  worker:
    build: .
    command: uv run celery -A config worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  beat:
    build: .
    command: uv run celery -A config beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
