# Generated by Django 5.1.7 on 2025-04-19 20:31

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_organization_profile_picture_organization_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(
                        3, "Username must be at least 3 characters long"
                    ),
                ],
            ),
        ),
    ]
