# Generated by Django 5.1.7 on 2025-03-27 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.verification.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.verification.models.generate_token,
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("type", models.CharField(choices=[("email", "Email")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_for", models.DurationField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
