# Generated by Django 5.1.7 on 2025-04-01 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationtoken",
            name="valid_for",
        ),
        migrations.AddField(
            model_name="verificationtoken",
            name="expire_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="verificationtoken",
            name="type",
            field=models.CharField(
                choices=[("email", "Email"), ("password_reset", "Password Reset")],
                max_length=20,
            ),
        ),
    ]
