# Generated by Django 5.1.7 on 2025-06-03 13:44

import uuid

from django.db import migrations, models


def populate_public_id(apps, schema_editor):
    VerificationToken = apps.get_model("verification", "VerificationToken")
    for token in VerificationToken.objects.all():
        token.public_id = uuid.uuid4()
        token.save(update_fields=["public_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0002_remove_verificationtoken_valid_for_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationtoken",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_public_id, reverse_code=migrations.RunPython.noop),
    ]
