# Generated by Django 5.1.7 on 2025-04-01 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[django.core.validators.RegexValidator("^09\\d{9}$")],
            ),
        ),
    ]
