# Generated by Django 5.1.7 on 2025-07-30 00:35

import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("authority", models.CharField(max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "pending"), ("s", "success"), ("c", "cancelled")], default="p", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("transaction_id", models.CharField(max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
