# Generated by Django 5.1.7 on 2025-05-31 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0007_speaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("currency", models.CharField(choices=[("IRR", "IRR"), ("IRT", "IRT")], max_length=3)),
                ("authority", models.CharField(max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "pending"), ("CONFIRMED", "confirmed"), ("CANCELLED", "cancelled")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("transaction_id", models.CharField(max_length=128, null=True)),
                (
                    "ticket",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="events.ticket",
                    ),
                ),
            ],
        ),
    ]
