# Generated by Django 5.1.7 on 2025-08-12 22:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_organization_phone"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("start", models.DecimalField(decimal_places=0, max_digits=12)),
                ("end", models.DecimalField(decimal_places=0, max_digits=12)),
                ("action", models.CharField(choices=[("p", "percentage"), ("c", "constant")], max_length=3)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="tickettransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="tickettransaction",
            name="authority",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tickettransaction",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="OrganizationAccounting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("service", models.CharField(choices=[("eventpayment", "event payment")], max_length=30)),
                ("balance", models.CharField(choices=[("dbt", "Debit"), ("crd", "Credit")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("extra_arguments", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
