# Generated by Django 5.1.7 on 2025-06-03 13:44

import django.utils.timezone
import uuid
from django.db import migrations, models


def populate_public_id(apps, schema_editor):
    TicketTransaction = apps.get_model("payment", "TicketTransaction")
    for ticket_transaction in TicketTransaction.objects.all():
        ticket_transaction.public_id = uuid.uuid4()
        ticket_transaction.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.RunPython(populate_public_id, reverse_code=migrations.RunPython.noop),
    ]
