# Generated by Django 5.1.7 on 2025-06-03 14:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_tickettransaction_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettransaction",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
