# Generated by Django 5.1.7 on 2025-06-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_tickettransaction_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='ticket',
        ),
    ]
