# Generated by Django 5.1.7 on 2025-07-27 20:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_tickettransaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start', models.DecimalField(decimal_places=0, max_digits=12)),
                ('end', models.DecimalField(decimal_places=0, max_digits=12)),
                ('action', models.CharField(choices=[('p', 'percentage'), ('c', 'constant')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'success'), ('c', 'cancelled')], default='p', max_length=20),
        ),
    ]
