# Generated by Django 5.1.7 on 2025-08-05 17:30

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="geo_location",
            field=models.JSONField(blank=True, null=True, validators=[apps.core.validators.geo_location_validator]),
        ),
    ]
