# Generated by Django 5.1.7 on 2025-08-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_geo_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("tg", "telegram"), ("in", "linkedin"), ("ig", "instagram")], max_length=10
                    ),
                ),
                ("url", models.URLField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "platform")},
            },
        ),
    ]
