# Generated by Django 5.1.7 on 2025-05-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_alter_organization_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="organization",
            name="image",
            field=models.ImageField(blank=True, upload_to="organizations/images/"),
        ),
    ]
