# Generated by Django 5.1.7 on 2025-06-03 13:44

import uuid
from django.db import migrations, models


def populate_public_id(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    for organization in Organization.objects.all():
        organization.public_id = uuid.uuid4()
        organization.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_public_id, reverse_code=migrations.RunPython.noop),
    ]
