# Generated by Django 5.1.7 on 2025-08-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_organizationsociallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator("^\\d+$")]
            ),
        ),
    ]
