# Generated by Django 5.1.7 on 2025-06-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='organization',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
